version: '3.8'

services:
  app:
    build:
      context: .
    container_name: go-fiber-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - air_data:/tmp
    depends_on:
      - postgres
    command: ["air", "-c", ".air.toml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata:
  air_data:
