version: '3'
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "54320:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  pgdata: